TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv9-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := kryo300

TARGET_BOARD_PLATFORM := kalama
TARGET_BOOTLOADER_BOARD_NAME := kalama
TARGET_NO_BOOTLOADER := true
TARGET_KERNEL_SOURCE := kernel/sony/sm8550
TARGET_KERNEL_VERSION := 5.15
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_COMPILE_WITH_MSM_KERNEL := true
BOARD_USES_QCOM_HARDWARE := true
QCOM_SOONG_NAMESPACE := hardware/qcom-caf/sm8550

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

include hardware/qcom-caf/common/BoardConfigQcom.mk

